name: Generate documentation PDF (REUSABLE)

on:
  workflow_call:
    inputs:
      VERSION:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Prepare
      - name: Checkout source code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.10"
      - name: Install doc dependencies
        run: pip install --no-cache-dir --require-hashes -r docs/requirements.txt && sudo apt update && sudo apt install -y libcairo2-dev libfreetype6-dev libffi-dev libjpeg-dev libpng-dev libz-dev
      - name: Install chromium
        run: sudo apt update && sudo apt install chromium-browser
      - name: Install node
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: 22
      - name: Install puppeteer
        run: cd docs && npm install
        env:
          PUPPETEER_SKIP_DOWNLOAD: "true"
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
      - name: Run mkdocs serve in background
        run: mkdocs serve -f mkdocs_print.yml & sleep 15
      - name: Run pdf script
        run: node docs/misc/pdf.js http://localhost:8000/print_page/ BunkerWeb_documentation_v${{ inputs.VERSION }}.pdf 'BunkerWeb documentation v${{ inputs.VERSION }}'
      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: BunkerWeb_documentation_v${{ inputs.VERSION }}.pdf
          path: BunkerWeb_documentation_v${{ inputs.VERSION }}.pdf
